package calc

// Code generated by peg calculator.peg DO NOT EDIT.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	rulee
	rulee1
	rulee2
	rulee3
	rulee4
	rulevalue
	rulevariable
	rulematrix
	ruleimaginary
	rulenumber
	ruleexp1
	ruleexp2
	rulenatural
	rulepi
	ruleprec
	rulesimplify
	rulederivative
	rulelog
	rulesqrt
	rulecos
	rulesin
	ruletan
	rulesub
	ruleadd
	ruleminus
	rulemultiply
	ruledivide
	rulemodulus
	ruleexponentiation
	ruleopen
	ruleclose
	rulesp
	rulerow
	rulePegText
)

var rul3s = [...]string{
	"Unknown",
	"e",
	"e1",
	"e2",
	"e3",
	"e4",
	"value",
	"variable",
	"matrix",
	"imaginary",
	"number",
	"exp1",
	"exp2",
	"natural",
	"pi",
	"prec",
	"simplify",
	"derivative",
	"log",
	"sqrt",
	"cos",
	"sin",
	"tan",
	"sub",
	"add",
	"minus",
	"multiply",
	"divide",
	"modulus",
	"exponentiation",
	"open",
	"close",
	"sp",
	"row",
	"PegText",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[34m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type Calculator struct {
	Buffer string
	buffer []rune
	rules  [35]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *Calculator) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *Calculator) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *Calculator
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *Calculator) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *Calculator) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func Pretty(pretty bool) func(*Calculator) error {
	return func(p *Calculator) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*Calculator) error {
	return func(p *Calculator) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *Calculator) Init(options ...func(*Calculator) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 e <- <(sp e1 !.)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				if !_rules[rulesp]() {
					goto l0
				}
				if !_rules[rulee1]() {
					goto l0
				}
				{
					position2, tokenIndex2 := position, tokenIndex
					if !matchDot() {
						goto l2
					}
					goto l0
				l2:
					position, tokenIndex = position2, tokenIndex2
				}
				add(rulee, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 e1 <- <(e2 ((add e2) / (minus e2))*)> */
		func() bool {
			position3, tokenIndex3 := position, tokenIndex
			{
				position4 := position
				if !_rules[rulee2]() {
					goto l3
				}
			l5:
				{
					position6, tokenIndex6 := position, tokenIndex
					{
						position7, tokenIndex7 := position, tokenIndex
						if !_rules[ruleadd]() {
							goto l8
						}
						if !_rules[rulee2]() {
							goto l8
						}
						goto l7
					l8:
						position, tokenIndex = position7, tokenIndex7
						if !_rules[ruleminus]() {
							goto l6
						}
						if !_rules[rulee2]() {
							goto l6
						}
					}
				l7:
					goto l5
				l6:
					position, tokenIndex = position6, tokenIndex6
				}
				add(rulee1, position4)
			}
			return true
		l3:
			position, tokenIndex = position3, tokenIndex3
			return false
		},
		/* 2 e2 <- <(e3 ((multiply e3) / (divide e3) / (modulus e3))*)> */
		func() bool {
			position9, tokenIndex9 := position, tokenIndex
			{
				position10 := position
				if !_rules[rulee3]() {
					goto l9
				}
			l11:
				{
					position12, tokenIndex12 := position, tokenIndex
					{
						position13, tokenIndex13 := position, tokenIndex
						if !_rules[rulemultiply]() {
							goto l14
						}
						if !_rules[rulee3]() {
							goto l14
						}
						goto l13
					l14:
						position, tokenIndex = position13, tokenIndex13
						if !_rules[ruledivide]() {
							goto l15
						}
						if !_rules[rulee3]() {
							goto l15
						}
						goto l13
					l15:
						position, tokenIndex = position13, tokenIndex13
						if !_rules[rulemodulus]() {
							goto l12
						}
						if !_rules[rulee3]() {
							goto l12
						}
					}
				l13:
					goto l11
				l12:
					position, tokenIndex = position12, tokenIndex12
				}
				add(rulee2, position10)
			}
			return true
		l9:
			position, tokenIndex = position9, tokenIndex9
			return false
		},
		/* 3 e3 <- <(e4 (exponentiation e4)*)> */
		func() bool {
			position16, tokenIndex16 := position, tokenIndex
			{
				position17 := position
				if !_rules[rulee4]() {
					goto l16
				}
			l18:
				{
					position19, tokenIndex19 := position, tokenIndex
					if !_rules[ruleexponentiation]() {
						goto l19
					}
					if !_rules[rulee4]() {
						goto l19
					}
					goto l18
				l19:
					position, tokenIndex = position19, tokenIndex19
				}
				add(rulee3, position17)
			}
			return true
		l16:
			position, tokenIndex = position16, tokenIndex16
			return false
		},
		/* 4 e4 <- <((minus value) / value)> */
		func() bool {
			position20, tokenIndex20 := position, tokenIndex
			{
				position21 := position
				{
					position22, tokenIndex22 := position, tokenIndex
					if !_rules[ruleminus]() {
						goto l23
					}
					if !_rules[rulevalue]() {
						goto l23
					}
					goto l22
				l23:
					position, tokenIndex = position22, tokenIndex22
					if !_rules[rulevalue]() {
						goto l20
					}
				}
			l22:
				add(rulee4, position21)
			}
			return true
		l20:
			position, tokenIndex = position20, tokenIndex20
			return false
		},
		/* 5 value <- <(matrix / imaginary / number / exp1 / exp2 / natural / pi / prec / simplify / derivative / log / sqrt / cos / sin / tan / variable / sub)> */
		func() bool {
			position24, tokenIndex24 := position, tokenIndex
			{
				position25 := position
				{
					position26, tokenIndex26 := position, tokenIndex
					if !_rules[rulematrix]() {
						goto l27
					}
					goto l26
				l27:
					position, tokenIndex = position26, tokenIndex26
					if !_rules[ruleimaginary]() {
						goto l28
					}
					goto l26
				l28:
					position, tokenIndex = position26, tokenIndex26
					if !_rules[rulenumber]() {
						goto l29
					}
					goto l26
				l29:
					position, tokenIndex = position26, tokenIndex26
					if !_rules[ruleexp1]() {
						goto l30
					}
					goto l26
				l30:
					position, tokenIndex = position26, tokenIndex26
					if !_rules[ruleexp2]() {
						goto l31
					}
					goto l26
				l31:
					position, tokenIndex = position26, tokenIndex26
					if !_rules[rulenatural]() {
						goto l32
					}
					goto l26
				l32:
					position, tokenIndex = position26, tokenIndex26
					if !_rules[rulepi]() {
						goto l33
					}
					goto l26
				l33:
					position, tokenIndex = position26, tokenIndex26
					if !_rules[ruleprec]() {
						goto l34
					}
					goto l26
				l34:
					position, tokenIndex = position26, tokenIndex26
					if !_rules[rulesimplify]() {
						goto l35
					}
					goto l26
				l35:
					position, tokenIndex = position26, tokenIndex26
					if !_rules[rulederivative]() {
						goto l36
					}
					goto l26
				l36:
					position, tokenIndex = position26, tokenIndex26
					if !_rules[rulelog]() {
						goto l37
					}
					goto l26
				l37:
					position, tokenIndex = position26, tokenIndex26
					if !_rules[rulesqrt]() {
						goto l38
					}
					goto l26
				l38:
					position, tokenIndex = position26, tokenIndex26
					if !_rules[rulecos]() {
						goto l39
					}
					goto l26
				l39:
					position, tokenIndex = position26, tokenIndex26
					if !_rules[rulesin]() {
						goto l40
					}
					goto l26
				l40:
					position, tokenIndex = position26, tokenIndex26
					if !_rules[ruletan]() {
						goto l41
					}
					goto l26
				l41:
					position, tokenIndex = position26, tokenIndex26
					if !_rules[rulevariable]() {
						goto l42
					}
					goto l26
				l42:
					position, tokenIndex = position26, tokenIndex26
					if !_rules[rulesub]() {
						goto l24
					}
				}
			l26:
				add(rulevalue, position25)
			}
			return true
		l24:
			position, tokenIndex = position24, tokenIndex24
			return false
		},
		/* 6 variable <- <(([A-Z] / [a-z])+ sp)> */
		func() bool {
			position43, tokenIndex43 := position, tokenIndex
			{
				position44 := position
				{
					position47, tokenIndex47 := position, tokenIndex
					if c := buffer[position]; c < rune('A') || c > rune('Z') {
						goto l48
					}
					position++
					goto l47
				l48:
					position, tokenIndex = position47, tokenIndex47
					if c := buffer[position]; c < rune('a') || c > rune('z') {
						goto l43
					}
					position++
				}
			l47:
			l45:
				{
					position46, tokenIndex46 := position, tokenIndex
					{
						position49, tokenIndex49 := position, tokenIndex
						if c := buffer[position]; c < rune('A') || c > rune('Z') {
							goto l50
						}
						position++
						goto l49
					l50:
						position, tokenIndex = position49, tokenIndex49
						if c := buffer[position]; c < rune('a') || c > rune('z') {
							goto l46
						}
						position++
					}
				l49:
					goto l45
				l46:
					position, tokenIndex = position46, tokenIndex46
				}
				if !_rules[rulesp]() {
					goto l43
				}
				add(rulevariable, position44)
			}
			return true
		l43:
			position, tokenIndex = position43, tokenIndex43
			return false
		},
		/* 7 matrix <- <('[' sp (e1 / row)+ ']' sp)> */
		func() bool {
			position51, tokenIndex51 := position, tokenIndex
			{
				position52 := position
				if buffer[position] != rune('[') {
					goto l51
				}
				position++
				if !_rules[rulesp]() {
					goto l51
				}
				{
					position55, tokenIndex55 := position, tokenIndex
					if !_rules[rulee1]() {
						goto l56
					}
					goto l55
				l56:
					position, tokenIndex = position55, tokenIndex55
					if !_rules[rulerow]() {
						goto l51
					}
				}
			l55:
			l53:
				{
					position54, tokenIndex54 := position, tokenIndex
					{
						position57, tokenIndex57 := position, tokenIndex
						if !_rules[rulee1]() {
							goto l58
						}
						goto l57
					l58:
						position, tokenIndex = position57, tokenIndex57
						if !_rules[rulerow]() {
							goto l54
						}
					}
				l57:
					goto l53
				l54:
					position, tokenIndex = position54, tokenIndex54
				}
				if buffer[position] != rune(']') {
					goto l51
				}
				position++
				if !_rules[rulesp]() {
					goto l51
				}
				add(rulematrix, position52)
			}
			return true
		l51:
			position, tokenIndex = position51, tokenIndex51
			return false
		},
		/* 8 imaginary <- <(<('-'? [0-9]+ ('.' [0-9]*)?)> 'i' sp)> */
		func() bool {
			position59, tokenIndex59 := position, tokenIndex
			{
				position60 := position
				{
					position61 := position
					{
						position62, tokenIndex62 := position, tokenIndex
						if buffer[position] != rune('-') {
							goto l62
						}
						position++
						goto l63
					l62:
						position, tokenIndex = position62, tokenIndex62
					}
				l63:
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l59
					}
					position++
				l64:
					{
						position65, tokenIndex65 := position, tokenIndex
						if c := buffer[position]; c < rune('0') || c > rune('9') {
							goto l65
						}
						position++
						goto l64
					l65:
						position, tokenIndex = position65, tokenIndex65
					}
					{
						position66, tokenIndex66 := position, tokenIndex
						if buffer[position] != rune('.') {
							goto l66
						}
						position++
					l68:
						{
							position69, tokenIndex69 := position, tokenIndex
							if c := buffer[position]; c < rune('0') || c > rune('9') {
								goto l69
							}
							position++
							goto l68
						l69:
							position, tokenIndex = position69, tokenIndex69
						}
						goto l67
					l66:
						position, tokenIndex = position66, tokenIndex66
					}
				l67:
					add(rulePegText, position61)
				}
				if buffer[position] != rune('i') {
					goto l59
				}
				position++
				if !_rules[rulesp]() {
					goto l59
				}
				add(ruleimaginary, position60)
			}
			return true
		l59:
			position, tokenIndex = position59, tokenIndex59
			return false
		},
		/* 9 number <- <(<('-'? [0-9]+ ('.' [0-9]*)?)> sp)> */
		func() bool {
			position70, tokenIndex70 := position, tokenIndex
			{
				position71 := position
				{
					position72 := position
					{
						position73, tokenIndex73 := position, tokenIndex
						if buffer[position] != rune('-') {
							goto l73
						}
						position++
						goto l74
					l73:
						position, tokenIndex = position73, tokenIndex73
					}
				l74:
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l70
					}
					position++
				l75:
					{
						position76, tokenIndex76 := position, tokenIndex
						if c := buffer[position]; c < rune('0') || c > rune('9') {
							goto l76
						}
						position++
						goto l75
					l76:
						position, tokenIndex = position76, tokenIndex76
					}
					{
						position77, tokenIndex77 := position, tokenIndex
						if buffer[position] != rune('.') {
							goto l77
						}
						position++
					l79:
						{
							position80, tokenIndex80 := position, tokenIndex
							if c := buffer[position]; c < rune('0') || c > rune('9') {
								goto l80
							}
							position++
							goto l79
						l80:
							position, tokenIndex = position80, tokenIndex80
						}
						goto l78
					l77:
						position, tokenIndex = position77, tokenIndex77
					}
				l78:
					add(rulePegText, position72)
				}
				if !_rules[rulesp]() {
					goto l70
				}
				add(rulenumber, position71)
			}
			return true
		l70:
			position, tokenIndex = position70, tokenIndex70
			return false
		},
		/* 10 exp1 <- <('e' 'x' 'p' open e1 close)> */
		func() bool {
			position81, tokenIndex81 := position, tokenIndex
			{
				position82 := position
				if buffer[position] != rune('e') {
					goto l81
				}
				position++
				if buffer[position] != rune('x') {
					goto l81
				}
				position++
				if buffer[position] != rune('p') {
					goto l81
				}
				position++
				if !_rules[ruleopen]() {
					goto l81
				}
				if !_rules[rulee1]() {
					goto l81
				}
				if !_rules[ruleclose]() {
					goto l81
				}
				add(ruleexp1, position82)
			}
			return true
		l81:
			position, tokenIndex = position81, tokenIndex81
			return false
		},
		/* 11 exp2 <- <('e' '^' value)> */
		func() bool {
			position83, tokenIndex83 := position, tokenIndex
			{
				position84 := position
				if buffer[position] != rune('e') {
					goto l83
				}
				position++
				if buffer[position] != rune('^') {
					goto l83
				}
				position++
				if !_rules[rulevalue]() {
					goto l83
				}
				add(ruleexp2, position84)
			}
			return true
		l83:
			position, tokenIndex = position83, tokenIndex83
			return false
		},
		/* 12 natural <- <('e' sp)> */
		func() bool {
			position85, tokenIndex85 := position, tokenIndex
			{
				position86 := position
				if buffer[position] != rune('e') {
					goto l85
				}
				position++
				if !_rules[rulesp]() {
					goto l85
				}
				add(rulenatural, position86)
			}
			return true
		l85:
			position, tokenIndex = position85, tokenIndex85
			return false
		},
		/* 13 pi <- <('p' 'i' sp)> */
		func() bool {
			position87, tokenIndex87 := position, tokenIndex
			{
				position88 := position
				if buffer[position] != rune('p') {
					goto l87
				}
				position++
				if buffer[position] != rune('i') {
					goto l87
				}
				position++
				if !_rules[rulesp]() {
					goto l87
				}
				add(rulepi, position88)
			}
			return true
		l87:
			position, tokenIndex = position87, tokenIndex87
			return false
		},
		/* 14 prec <- <('p' 'r' 'e' 'c' open e1 close)> */
		func() bool {
			position89, tokenIndex89 := position, tokenIndex
			{
				position90 := position
				if buffer[position] != rune('p') {
					goto l89
				}
				position++
				if buffer[position] != rune('r') {
					goto l89
				}
				position++
				if buffer[position] != rune('e') {
					goto l89
				}
				position++
				if buffer[position] != rune('c') {
					goto l89
				}
				position++
				if !_rules[ruleopen]() {
					goto l89
				}
				if !_rules[rulee1]() {
					goto l89
				}
				if !_rules[ruleclose]() {
					goto l89
				}
				add(ruleprec, position90)
			}
			return true
		l89:
			position, tokenIndex = position89, tokenIndex89
			return false
		},
		/* 15 simplify <- <('s' 'i' 'm' 'p' 'l' 'i' 'f' 'y' open e1 close)> */
		func() bool {
			position91, tokenIndex91 := position, tokenIndex
			{
				position92 := position
				if buffer[position] != rune('s') {
					goto l91
				}
				position++
				if buffer[position] != rune('i') {
					goto l91
				}
				position++
				if buffer[position] != rune('m') {
					goto l91
				}
				position++
				if buffer[position] != rune('p') {
					goto l91
				}
				position++
				if buffer[position] != rune('l') {
					goto l91
				}
				position++
				if buffer[position] != rune('i') {
					goto l91
				}
				position++
				if buffer[position] != rune('f') {
					goto l91
				}
				position++
				if buffer[position] != rune('y') {
					goto l91
				}
				position++
				if !_rules[ruleopen]() {
					goto l91
				}
				if !_rules[rulee1]() {
					goto l91
				}
				if !_rules[ruleclose]() {
					goto l91
				}
				add(rulesimplify, position92)
			}
			return true
		l91:
			position, tokenIndex = position91, tokenIndex91
			return false
		},
		/* 16 derivative <- <('d' 'e' 'r' 'i' 'v' 'a' 't' 'i' 'v' 'e' open e1 close)> */
		func() bool {
			position93, tokenIndex93 := position, tokenIndex
			{
				position94 := position
				if buffer[position] != rune('d') {
					goto l93
				}
				position++
				if buffer[position] != rune('e') {
					goto l93
				}
				position++
				if buffer[position] != rune('r') {
					goto l93
				}
				position++
				if buffer[position] != rune('i') {
					goto l93
				}
				position++
				if buffer[position] != rune('v') {
					goto l93
				}
				position++
				if buffer[position] != rune('a') {
					goto l93
				}
				position++
				if buffer[position] != rune('t') {
					goto l93
				}
				position++
				if buffer[position] != rune('i') {
					goto l93
				}
				position++
				if buffer[position] != rune('v') {
					goto l93
				}
				position++
				if buffer[position] != rune('e') {
					goto l93
				}
				position++
				if !_rules[ruleopen]() {
					goto l93
				}
				if !_rules[rulee1]() {
					goto l93
				}
				if !_rules[ruleclose]() {
					goto l93
				}
				add(rulederivative, position94)
			}
			return true
		l93:
			position, tokenIndex = position93, tokenIndex93
			return false
		},
		/* 17 log <- <('l' 'o' 'g' open e1 close)> */
		func() bool {
			position95, tokenIndex95 := position, tokenIndex
			{
				position96 := position
				if buffer[position] != rune('l') {
					goto l95
				}
				position++
				if buffer[position] != rune('o') {
					goto l95
				}
				position++
				if buffer[position] != rune('g') {
					goto l95
				}
				position++
				if !_rules[ruleopen]() {
					goto l95
				}
				if !_rules[rulee1]() {
					goto l95
				}
				if !_rules[ruleclose]() {
					goto l95
				}
				add(rulelog, position96)
			}
			return true
		l95:
			position, tokenIndex = position95, tokenIndex95
			return false
		},
		/* 18 sqrt <- <('s' 'q' 'r' 't' open e1 close)> */
		func() bool {
			position97, tokenIndex97 := position, tokenIndex
			{
				position98 := position
				if buffer[position] != rune('s') {
					goto l97
				}
				position++
				if buffer[position] != rune('q') {
					goto l97
				}
				position++
				if buffer[position] != rune('r') {
					goto l97
				}
				position++
				if buffer[position] != rune('t') {
					goto l97
				}
				position++
				if !_rules[ruleopen]() {
					goto l97
				}
				if !_rules[rulee1]() {
					goto l97
				}
				if !_rules[ruleclose]() {
					goto l97
				}
				add(rulesqrt, position98)
			}
			return true
		l97:
			position, tokenIndex = position97, tokenIndex97
			return false
		},
		/* 19 cos <- <('c' 'o' 's' open e1 close)> */
		func() bool {
			position99, tokenIndex99 := position, tokenIndex
			{
				position100 := position
				if buffer[position] != rune('c') {
					goto l99
				}
				position++
				if buffer[position] != rune('o') {
					goto l99
				}
				position++
				if buffer[position] != rune('s') {
					goto l99
				}
				position++
				if !_rules[ruleopen]() {
					goto l99
				}
				if !_rules[rulee1]() {
					goto l99
				}
				if !_rules[ruleclose]() {
					goto l99
				}
				add(rulecos, position100)
			}
			return true
		l99:
			position, tokenIndex = position99, tokenIndex99
			return false
		},
		/* 20 sin <- <('s' 'i' 'n' open e1 close)> */
		func() bool {
			position101, tokenIndex101 := position, tokenIndex
			{
				position102 := position
				if buffer[position] != rune('s') {
					goto l101
				}
				position++
				if buffer[position] != rune('i') {
					goto l101
				}
				position++
				if buffer[position] != rune('n') {
					goto l101
				}
				position++
				if !_rules[ruleopen]() {
					goto l101
				}
				if !_rules[rulee1]() {
					goto l101
				}
				if !_rules[ruleclose]() {
					goto l101
				}
				add(rulesin, position102)
			}
			return true
		l101:
			position, tokenIndex = position101, tokenIndex101
			return false
		},
		/* 21 tan <- <('t' 'a' 'n' open e1 close)> */
		func() bool {
			position103, tokenIndex103 := position, tokenIndex
			{
				position104 := position
				if buffer[position] != rune('t') {
					goto l103
				}
				position++
				if buffer[position] != rune('a') {
					goto l103
				}
				position++
				if buffer[position] != rune('n') {
					goto l103
				}
				position++
				if !_rules[ruleopen]() {
					goto l103
				}
				if !_rules[rulee1]() {
					goto l103
				}
				if !_rules[ruleclose]() {
					goto l103
				}
				add(ruletan, position104)
			}
			return true
		l103:
			position, tokenIndex = position103, tokenIndex103
			return false
		},
		/* 22 sub <- <(open e1 close)> */
		func() bool {
			position105, tokenIndex105 := position, tokenIndex
			{
				position106 := position
				if !_rules[ruleopen]() {
					goto l105
				}
				if !_rules[rulee1]() {
					goto l105
				}
				if !_rules[ruleclose]() {
					goto l105
				}
				add(rulesub, position106)
			}
			return true
		l105:
			position, tokenIndex = position105, tokenIndex105
			return false
		},
		/* 23 add <- <('+' sp)> */
		func() bool {
			position107, tokenIndex107 := position, tokenIndex
			{
				position108 := position
				if buffer[position] != rune('+') {
					goto l107
				}
				position++
				if !_rules[rulesp]() {
					goto l107
				}
				add(ruleadd, position108)
			}
			return true
		l107:
			position, tokenIndex = position107, tokenIndex107
			return false
		},
		/* 24 minus <- <('-' sp)> */
		func() bool {
			position109, tokenIndex109 := position, tokenIndex
			{
				position110 := position
				if buffer[position] != rune('-') {
					goto l109
				}
				position++
				if !_rules[rulesp]() {
					goto l109
				}
				add(ruleminus, position110)
			}
			return true
		l109:
			position, tokenIndex = position109, tokenIndex109
			return false
		},
		/* 25 multiply <- <('*' sp)> */
		func() bool {
			position111, tokenIndex111 := position, tokenIndex
			{
				position112 := position
				if buffer[position] != rune('*') {
					goto l111
				}
				position++
				if !_rules[rulesp]() {
					goto l111
				}
				add(rulemultiply, position112)
			}
			return true
		l111:
			position, tokenIndex = position111, tokenIndex111
			return false
		},
		/* 26 divide <- <('/' sp)> */
		func() bool {
			position113, tokenIndex113 := position, tokenIndex
			{
				position114 := position
				if buffer[position] != rune('/') {
					goto l113
				}
				position++
				if !_rules[rulesp]() {
					goto l113
				}
				add(ruledivide, position114)
			}
			return true
		l113:
			position, tokenIndex = position113, tokenIndex113
			return false
		},
		/* 27 modulus <- <('%' sp)> */
		func() bool {
			position115, tokenIndex115 := position, tokenIndex
			{
				position116 := position
				if buffer[position] != rune('%') {
					goto l115
				}
				position++
				if !_rules[rulesp]() {
					goto l115
				}
				add(rulemodulus, position116)
			}
			return true
		l115:
			position, tokenIndex = position115, tokenIndex115
			return false
		},
		/* 28 exponentiation <- <('^' sp)> */
		func() bool {
			position117, tokenIndex117 := position, tokenIndex
			{
				position118 := position
				if buffer[position] != rune('^') {
					goto l117
				}
				position++
				if !_rules[rulesp]() {
					goto l117
				}
				add(ruleexponentiation, position118)
			}
			return true
		l117:
			position, tokenIndex = position117, tokenIndex117
			return false
		},
		/* 29 open <- <('(' sp)> */
		func() bool {
			position119, tokenIndex119 := position, tokenIndex
			{
				position120 := position
				if buffer[position] != rune('(') {
					goto l119
				}
				position++
				if !_rules[rulesp]() {
					goto l119
				}
				add(ruleopen, position120)
			}
			return true
		l119:
			position, tokenIndex = position119, tokenIndex119
			return false
		},
		/* 30 close <- <(')' sp)> */
		func() bool {
			position121, tokenIndex121 := position, tokenIndex
			{
				position122 := position
				if buffer[position] != rune(')') {
					goto l121
				}
				position++
				if !_rules[rulesp]() {
					goto l121
				}
				add(ruleclose, position122)
			}
			return true
		l121:
			position, tokenIndex = position121, tokenIndex121
			return false
		},
		/* 31 sp <- <(' ' / '\t')*> */
		func() bool {
			{
				position124 := position
			l125:
				{
					position126, tokenIndex126 := position, tokenIndex
					{
						position127, tokenIndex127 := position, tokenIndex
						if buffer[position] != rune(' ') {
							goto l128
						}
						position++
						goto l127
					l128:
						position, tokenIndex = position127, tokenIndex127
						if buffer[position] != rune('\t') {
							goto l126
						}
						position++
					}
				l127:
					goto l125
				l126:
					position, tokenIndex = position126, tokenIndex126
				}
				add(rulesp, position124)
			}
			return true
		},
		/* 32 row <- <(';' sp)> */
		func() bool {
			position129, tokenIndex129 := position, tokenIndex
			{
				position130 := position
				if buffer[position] != rune(';') {
					goto l129
				}
				position++
				if !_rules[rulesp]() {
					goto l129
				}
				add(rulerow, position130)
			}
			return true
		l129:
			position, tokenIndex = position129, tokenIndex129
			return false
		},
		nil,
	}
	p.rules = _rules
	return nil
}
